# Generated by Django 4.1.7 on 2023-04-02 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertoken',
            options={'ordering': ['-expiry_date'], 'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
    ]
