# Generated by Django 4.1.7 on 2023-04-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0002_alter_usertoken_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expiry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
